plugins:
'@csstools/postcss-global-data':
  files:
    - src/shared/theme/breakpoints.css

postcss-nested: {}

postcss-preset-env:
  stage: 3
  browsers: '> 1%'
  features:
    custom-media-queries: true
    nesting-rules: true
    logical-properties-and-values: true
  autoprefixer: true
  preserve: false
